<?php

/**
 * Audit files carries out a simple audit of the Drupal upload directory
 * and the {files} table, to look for inconsistencies
 */


/**
 * Implements hook_help().
 */
function auditfiles_help($path, $arg) {
  switch ($path) {
    case 'admin/config/auditfiles':
      return t('You can choose to exclude specific files, paths and extensions from the \'files
        not in database\' audit report by adding them to the relevant lists below.');
    case 'admin/help#auditfiles':
      return '<p>' . t('The audit files module performs an audit of the file table and the files
        directory to check for inconsistencies.') . '</p>';
    case 'admin/reports/auditfiles':
      $output = '<p>' . t('The files listed below are in the files directory on the server but
        appear to have no corresponding entry in the {file_managed} table. Files in "temporary" folders
        such as those created by the image module are included in order to check that they are not
        filling up. You can choose to delete files from this report but remember that if you do
        this the action cannot be undone. You can also add files to the {file_managed} table - you might
        do this if you have uploaded files outside of Drupal (e.g., by ftp) and will be attaching
        them to nodes through the other tools.') . '</p>';
      $output .= '<p>' . t('Files in this list are relative to the files directory %directorypath.', array('%directorypath' => file_default_scheme())) . '</p>';
      // If on a confirmation form then suppress the help message
      if (array_key_exists('operation', $_POST) && $_POST['operation'] == 'delete' && array_key_exists('files', $_POST)) {
        $output = '';
      }
      return $output;
    case 'admin/reports/auditfiles/notonserver':
      $output = '<p>' . t('The files listed below are in the {file_managed} table but the physical files
        do not exist on the server. This might mean the file has been deleted using a program such
        as FTP, or it may mean there is an error in the database.</p><p>If the file was uploaded
        using the upload module then you can click on the node number to view the item to which
        the missing file relates to try and determine what action needs to be taken, or you can
        click the edit link to open the node editing form directly.') . '</p>';
      $output .= '<p>' . t('Files in this list are relative to the files directory %directorypath.',
        array('%directorypath' => file_default_scheme())) . '</p>';
      return $output;
    case 'admin/reports/auditfiles/references':
      $output = '<p>' . t('Listed here are file references embedded in node bodies which do
        not have exact correspondences in the {file_managed} and {upload} tables. If there is a file
        in the {file_managed} table with a corresponding base name, that is listed. Scenarios are:
        <ul><li><strong>No match at all in the {file_managed} table.</strong> Go to <strong>Files
        not in database</strong> and make sure any files that exist have been added to the database.
        If they have, you should either find and upload the missing file and run this report
        again, or remove the reference from the node.</li>
        <li><strong>Multiple matches in the {file_managed} table.</strong> This can happen when the same
        filename is in multiple directories in the uploded file hierarchy. You can review the
        alternate files and delete any that are true duplicates. When different files have the
        same basename, you can select the one that goes with the given node and choose
        <strong>Attach selected files</strong>. This will rewrite the reference in the node
        to use the canonical relative URL to the file, and if necessary add the reference
        to the {upload} table.</li>
        <li><strong>A single match in the {file_managed} table.</strong> You can make the attachments
        between these nodes and the corresponding files one-by-one by selecting them and choosing
        <strong>Attach selected files</strong>, or automatically apply it to all single-match
        cases with <strong>Attach all unique matches</strong>.</li></ul>') . '</p>';
      $output .= '<p>' . t('Files in this list are relative to the files directory %directorypath.',
        array('%directorypath' => file_default_scheme())) . '</p>';
      return $output;
    case 'admin/reports/auditfiles/unreferenced':
      $output = '<p>' . t('The files listed below are in the {file_managed} table but no nodes are recorded
        as referencing them (i.e., there\'s no entry in the {upload} table). This might mean the
        node has been deleted without deleting the file, or that the files were uploaded by some
        means other than the upload module (e.g., ftp) and the relationships between files and
        nodes have not been made. If you have used the <strong>Missing references</strong> report
        and accounted for all files that should be referenced, and are sure that the files below
        are not needed, you can delete them. Click on the basename to get a list of all nodes
        referencing that base filename (the <strong>Missing references</strong> report only
        identifies <strong>&lt;img&gt;</strong> and <strong>window.open</strong> references,
        this may help you identify if the file is referenced by another means).') . '</p>';
      $output .= '<p>' . t('Files in this list are relative to the files directory %directorypath.',
        array('%directorypath' => file_default_scheme())) . '</p>';
      return $output;
  }
}


/**
 * Implements hook_permission().
 */
function auditfiles_permission() {
  return array(
    'access file audits' => array(
      'title' => t('access file audits'),
      'description' => t('Allow access to file audits.'),
    ),
    'administer file audits' => array(
      'title' => t('administer file audits'),
      'description' => t('Perform administration tasks for the Audit files module.'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function auditfiles_menu() {
  $items = array();

  // Configure the settings for this module.
  $items['admin/config/system/auditfiles'] = array(
    'title' => 'Audit files',
    'description' => 'Set file, extension and path exclusions for file audits.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('auditfiles_admin_settings'),
    'access arguments' => array('administer file audits'),
    'file' => 'auditfiles.admin.inc',
  );

  // The various reports.
  $items['admin/reports/auditfiles'] = array(
    'title' => 'Audit files',
    'description' => 'List files that are not on the server or not in the database.',
    'page callback' => 'auditfiles_notindb',
    'access arguments' => array('access file audits'),
    'file' => 'auditfiles.notindb.inc',
  );
  $items['admin/reports/auditfiles/notindb'] = array(
    'title' => 'Not in database',
    'description' => 'List files that are on the server but are not in the database.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/reports/auditfiles/notonserver'] = array(
    'title' => 'Not on server',
    'description' => 'List files that are in the database, but are not on the server.',
    'page callback' => 'auditfiles_notonserver',
    'access arguments' => array('access file audits'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'auditfiles.notonserver.inc',
    'weight' => -5,
  );
  $items['admin/reports/auditfiles/references'] = array(
    'title' => 'Missing references',
    'description' => 'List files referenced by nodes, but not properly linked or attached.',
    'page callback' => 'auditfiles_references',
    'access arguments' => array('access file audits'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'auditfiles.references.inc',
    'weight' => 0,
  );
  $items['admin/reports/auditfiles/unreferenced'] = array(
    'title' => 'Unreferenced',
    'description' => 'List files that are in the database, but are not referenced by any node.',
    'page callback' => 'auditfiles_unreferenced',
    'access arguments' => array('access file audits'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'auditfiles.unreferenced.inc',
    'weight' => 5,
  );
  $items['admin/reports/auditfiles/unreferenced/%'] = array(
    'title' => 'Referencing nodes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('auditfiles_node_references_form', 4),
    'access arguments' => array('access file audits'),
    'type' => MENU_CALLBACK,
    'file' => 'auditfiles.unreferenced.inc',
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function auditfiles_theme() {
  return array(
    'auditfiles_notindb_form' => array(
      'render element' => 'form',
      'file' => 'auditfiles.notindb.inc',
    ),
    'auditfiles_unreferenced_form' => array(
      'render element' => 'form',
      'file' => 'auditfiles.unreferenced.inc',
    ),
    'auditfiles_node_references_form' => array(
      'render element' => 'form',
      'file' => 'auditfiles.unreferenced.inc',
    ),
    'auditfiles_references_form' => array(
      'render element' => 'form',
      'file' => 'auditfiles.references.inc',
    ),
  );
}
